"""empty message

Revision ID: 08bc20ca41e3
Revises: a431ae7d0b69
Create Date: 2019-03-05 17:07:08.784500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08bc20ca41e3'
down_revision = 'a431ae7d0b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'areas', 'areas', ['pid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'areas', type_='foreignkey')
    # ### end Alembic commands ###
