"""empty message

Revision ID: 993c8ee6b44c
Revises: 036e54b1b12a
Create Date: 2019-03-05 16:43:43.329112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993c8ee6b44c'
down_revision = '036e54b1b12a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'areas', 'areas', ['pid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'areas', type_='foreignkey')
    # ### end Alembic commands ###
